ERROR    root:test_httpRun.py:134 assert False != False
 +  where False = <model.http_model.http_model object at 0x000001AF9B6FA6E0>.assert_value
INFO     root:logDecoratorl.py:39 
>>===============================正在执行第2条用例======================================>>
测试标题: 密码错误，登录失败
请求方式: post
请求头:   {'accesstoken': '17b471073252f2cc3790c054591aaf18', 'timespan': '1660615538'}
请求路径: http://110.80.137.11:8051/Users/Login_UserName
传参方式： params
请求内容: {
                "phone": "",
                "username":18190335520,
                "password": "QTEyMzQ2ag==",
                "code": "",
                "invitecode": ""
            }
依赖测试用例: 暂无依赖用例数据
接口响应内容: {"success":false,"msg":"密码不正确","code":"","data":null}
接口响应时长: 0.082559 s
Http状态码: 200
断言方式：不等于
期望结果：False
实际结果：[False]
>>==============================第2条用例执行完毕=======================================>>